name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job:
    name: Build
    runs-on: ubuntu-latest
    container: node:20.2
    steps:
      - uses: actions/checkout@v3
      - run: npm install && npx marp slides.md
